---
- name: Create Main network
  community.docker.docker_network:
    name: nginx
    state: present
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: nginx

- name: Pull nginx Latest images
  ansible.builtin.docker_image:
    name: "{{ item }}"
    source: pull
  ignore_errors: true
  loop:
    - nginx

- name: Create directories
  file:
    force: false
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /data/configs, owner: "1000", group: "root", mode: "0775" }

- name: Deploy managed files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: default.conf, dest: /data/default.conf, owner: "root", group: "root", mode: "0644" }

- name: nginx container is created
  community.docker.docker_container:
    name: nginx
    hostname: nginx
    image: nginx
    state: present
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /data/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/configs:/configs:rw
    networks_cli_compatible: true
    networks:
      - name: nginx

- name: nginx container is running
  community.docker.docker_container:
    name: nginx
    state: started
