---
# tasks file for docker
- name: Install packages
  tags: install
  apt:
   update_cache: yes 
   force_apt_get: yes
   state: present   
   pkg: "{{ item }}"
  with_items:
   - "{{ pkgs2_var }}"
  when: not flush_all_env|bool

- name: Install key gpg from docker.com
  tags: install
  apt_key:
   url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
   state: present
  when: not flush_all_env|bool

- name: Add repository to apt
  tags: install
  apt_repository:
   repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ansible_distribution_release}} stable
   state: present
  when: not flush_all_env|bool
  register: docker_key_output

- name: Install docker
  tags: install
  apt:
   update_cache: yes
   force_apt_get: yes
   state: present
   pkg: "{{ item }}"
  with_items:
   - "{{ pkgs1_var }}"
  when: not flush_all_env|bool

- name: Logrotate for containers!
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "docker-logrotate", dest: "/etc/logrotate.d/docker-logrotate", owner: "root", group: "root", mode: "0644"  }

- name: Apply new logrotate setting
  ansible.builtin.shell:
    cmd: "logrotate /etc/logrotate.d/docker-logrotate"
